<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CitasApp.Aplications\CitasApp.Aplications.csproj" />
    <ProjectReference Include="..\CitasApp.Domain\CitasApp.Domain.csproj" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="EntityFramework" Version="6.5.2" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
		<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
	</ItemGroup>

</Project>
