<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\..\OneDrive\Desktop\veryyyfosfioew\ArqSoft-S05-Josue-CI-CD\Infrastructure\Repositories\CsvCitaRepository.cs" Link="Repositories\CsvCitaRepository.cs" />
    <Compile Include="..\..\..\..\OneDrive\Desktop\veryyyfosfioew\ArqSoft-S05-Josue-CI-CD\Infrastructure\Repositories\CsvMedicoRepository.cs" Link="Repositories\CsvMedicoRepository.cs" />
    <Compile Include="..\..\..\..\OneDrive\Desktop\veryyyfosfioew\ArqSoft-S05-Josue-CI-CD\Infrastructure\Repositories\CsvPacienteRepository.cs" Link="Repositories\CsvPacienteRepository.cs" />
    <Compile Include="..\..\..\..\OneDrive\Desktop\veryyyfosfioew\ArqSoft-S05-Josue-CI-CD\Infrastructure\Repositories\JsonCitaRepository.cs" Link="Repositories\JsonCitaRepository.cs" />
    <Compile Include="..\..\..\..\OneDrive\Desktop\veryyyfosfioew\ArqSoft-S05-Josue-CI-CD\Infrastructure\Repositories\JsonMedicoRepository.cs" Link="Repositories\JsonMedicoRepository.cs" />
    <Compile Include="..\..\..\..\OneDrive\Desktop\veryyyfosfioew\ArqSoft-S05-Josue-CI-CD\Infrastructure\Repositories\JsonPacienteRepository.cs" Link="Repositories\JsonPacienteRepository.cs" />
    <Compile Include="..\..\..\..\OneDrive\Desktop\veryyyfosfioew\ArqSoft-S05-Josue-CI-CD\Infrastructure\Repositories\LoggingPacienteRepository.cs" Link="Repositories\LoggingPacienteRepository.cs" />
    <Compile Include="..\..\..\..\OneDrive\Desktop\veryyyfosfioew\ArqSoft-S05-Josue-CI-CD\Infrastructure\Repositories\MemoriaPacienteRepository.cs" Link="Repositories\MemoriaPacienteRepository.cs" />
    <Compile Include="..\..\..\..\OneDrive\Desktop\veryyyfosfioew\ArqSoft-S05-Josue-CI-CD\Infrastructure\Repositories\RepositoryFactory.cs" Link="Repositories\RepositoryFactory.cs" />
    <Compile Include="..\..\..\..\OneDrive\Desktop\veryyyfosfioew\ArqSoft-S05-Josue-CI-CD\Infrastructure\Repositories\SqliteCitaRepository.cs" Link="Repositories\SqliteCitaRepository.cs" />
    <Compile Include="..\..\..\..\OneDrive\Desktop\veryyyfosfioew\ArqSoft-S05-Josue-CI-CD\Infrastructure\Repositories\SqliteMedicoRepository.cs" Link="Repositories\SqliteMedicoRepository.cs" />
    <Compile Include="..\..\..\..\OneDrive\Desktop\veryyyfosfioew\ArqSoft-S05-Josue-CI-CD\Infrastructure\Repositories\SqlitePacienteRepository.cs" Link="Repositories\SqlitePacienteRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Citas_App.Domain\Citas_App.Domain.csproj" />
  </ItemGroup>

</Project>
